require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"ASCC":[function(require,module,exports){
var _calculateDistance, _chooseGesture, _deltas, _drag, _updateVelocity, distance, timeOut;

_deltas = [];

timeOut = 100;

distance = 0;

exports.gesture = null;

exports.minDistance = 110;

exports.minGestureVelocity = 1.786;

exports.appSwitcher = function(calcbot, spotify, alto, recents, icons, calcbotIcon, curve) {
  calcbot.draggable.enabled = false;
  calcbot.on(Events.Click, function() {
    calcbot.animateStop();
    spotify.animateStop();
    alto.animateStop();
    icons.animateStop();
    recents.animateStop();
    calcbot.states["switch"]("app", {
      curve: curve
    });
    spotify.states["switch"]("app", {
      curve: curve
    });
    alto.states["switch"]("app", {
      curve: curve
    });
    icons.states["switch"]("app", {
      curve: curve
    });
    recents.states["switch"]("app");
    calcbot.draggable.enabled = true;
  });
  return calcbotIcon.on(Events.Click, function() {
    calcbot.animateStop();
    spotify.animateStop();
    alto.animateStop();
    icons.animateStop();
    recents.animateStop();
    calcbot.states["switch"]("app", {
      curve: curve
    });
    spotify.states["switch"]("app", {
      curve: curve
    });
    alto.states["switch"]("app", {
      curve: curve
    });
    icons.states["switch"]("app", {
      curve: curve
    });
    recents.states["switch"]("app");
    calcbot.draggable.enabled = true;
  });
};

exports.calculateVelocity = function(event, calcbot, controlCenter, recents, originY) {
  var curr, prev, time, timeSinceLastMove, velocity;
  if (_deltas.length < 2) {
    return 0;
  }
  curr = _deltas.slice(-2, -1)[0];
  prev = _deltas.slice(-1)[0];
  time = curr.t - prev.t;
  velocity = ((curr.y - prev.y) / time) * -1;
  timeSinceLastMove = new Date().getTime() - prev.t;
  if (timeSinceLastMove > timeOut) {
    return 0;
  }
  if (isNaN(velocity) === true) {
    return 0;
  }
  calcbot.emit("calculateDistance", event, calcbot, recents, originY);
  calcbot.emit("chooseGesture", velocity, calcbot, controlCenter);
  return velocity;
};

exports.makeDraggable = function(layer, speedX, speedY) {
  layer.draggable.enabled = true;
  layer.draggable.speedX = speedX;
  return layer.draggable.speedY = speedY;
};

exports.removeListeners = function() {
  var velocity;
  document.removeEventListener(Events.TouchMove, _updateVelocity);
  exports.gesture = null;
  _deltas = [];
  return velocity = 0;
};

exports.addListeners = function(calcbot) {
  document.addEventListener(Events.TouchMove, _updateVelocity);
  calcbot.once("chooseGesture", _chooseGesture);
  return calcbot.on("calculateDistance", _calculateDistance);
};

_calculateDistance = function(event, calcbot, recents, originY) {
  distance = originY - event.pageY;
  if (exports.gesture === "Drag") {
    return _drag(distance, calcbot, recents);
  } else {

  }
};

_drag = function(distance, calcbot, recents) {
  calcbot.scale = Utils.modulate(distance, [0, 657], [1, .4867], true);
  return recents.opacity = Utils.modulate(calcbot.scale, [.70, .4867], [0, 1], true);
};

_chooseGesture = function(velocity, calcbot, controlCenter) {
  if (velocity < exports.minGestureVelocity && distance < exports.minDistance) {
    return exports.gesture = "Drag";
  } else {
    calcbot.draggable.enabled = false;
    return controlCenter.states["switch"]("open", {
      curve: "spring(550, 25, 0)"
    });
  }
};

_updateVelocity = function(event) {
  var updatedDelta;
  updatedDelta = {
    y: event.pageY,
    t: event.timeStamp
  };
  return _deltas.push(updatedDelta);
};



},{}],"ASCC":[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
var _calculateDistance, _chooseGesture, _deltas, _drag, _updateVelocity, distance, timeOut;

_deltas = [];

timeOut = 100;

distance = 0;

exports.gesture = null;

exports.minDistance = 110;

exports.minGestureVelocity = 1.786;

exports.appSwitcher = function(calcbot, spotify, alto, recents, icons, calcbotIcon, curve) {
  calcbot.draggable.enabled = false;
  calcbot.on(Events.Click, function() {
    calcbot.animateStop();
    spotify.animateStop();
    alto.animateStop();
    icons.animateStop();
    recents.animateStop();
    calcbot.states["switch"]("app", {
      curve: curve
    });
    spotify.states["switch"]("app", {
      curve: curve
    });
    alto.states["switch"]("app", {
      curve: curve
    });
    icons.states["switch"]("app", {
      curve: curve
    });
    recents.states["switch"]("app");
    calcbot.draggable.enabled = true;
  });
  return calcbotIcon.on(Events.Click, function() {
    calcbot.animateStop();
    spotify.animateStop();
    alto.animateStop();
    icons.animateStop();
    recents.animateStop();
    calcbot.states["switch"]("app", {
      curve: curve
    });
    spotify.states["switch"]("app", {
      curve: curve
    });
    alto.states["switch"]("app", {
      curve: curve
    });
    icons.states["switch"]("app", {
      curve: curve
    });
    recents.states["switch"]("app");
    calcbot.draggable.enabled = true;
  });
};

exports.calculateVelocity = function(event, calcbot, controlCenter, recents, originY) {
  var curr, prev, time, timeSinceLastMove, velocity;
  if (_deltas.length < 2) {
    return 0;
  }
  curr = _deltas.slice(-2, -1)[0];
  prev = _deltas.slice(-1)[0];
  time = curr.t - prev.t;
  velocity = ((curr.y - prev.y) / time) * -1;
  timeSinceLastMove = new Date().getTime() - prev.t;
  if (timeSinceLastMove > timeOut) {
    return 0;
  }
  if (isNaN(velocity) === true) {
    return 0;
  }
  calcbot.emit("calculateDistance", event, calcbot, recents, originY);
  calcbot.emit("chooseGesture", velocity, calcbot, controlCenter);
  return velocity;
};

exports.makeDraggable = function(layer, speedX, speedY) {
  layer.draggable.enabled = true;
  layer.draggable.speedX = speedX;
  return layer.draggable.speedY = speedY;
};

exports.removeListeners = function() {
  var velocity;
  document.removeEventListener(Events.TouchMove, _updateVelocity);
  exports.gesture = null;
  _deltas = [];
  return velocity = 0;
};

exports.addListeners = function(calcbot) {
  document.addEventListener(Events.TouchMove, _updateVelocity);
  calcbot.once("chooseGesture", _chooseGesture);
  return calcbot.on("calculateDistance", _calculateDistance);
};

_calculateDistance = function(event, calcbot, recents, originY) {
  distance = originY - event.pageY;
  if (exports.gesture === "Drag") {
    return _drag(distance, calcbot, recents);
  } else {

  }
};

_drag = function(distance, calcbot, recents) {
  calcbot.scale = Utils.modulate(distance, [0, 657], [1, .4867], true);
  return recents.opacity = Utils.modulate(calcbot.scale, [.70, .4867], [0, 1], true);
};

_chooseGesture = function(velocity, calcbot, controlCenter) {
  if (velocity < exports.minGestureVelocity && distance < exports.minDistance) {
    return exports.gesture = "Drag";
  } else {
    calcbot.draggable.enabled = false;
    return controlCenter.states["switch"]("open", {
      curve: "spring(550, 25, 0)"
    });
  }
};

_updateVelocity = function(event) {
  var updatedDelta;
  updatedDelta = {
    y: event.pageY,
    t: event.timeStamp
  };
  return _deltas.push(updatedDelta);
};

},{}]},{},[])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCIvVXNlcnMvam9zaG10dWNrZXIvR2l0SHViL0FTQ0MvQVNDQy5mcmFtZXIvbW9kdWxlcy9BU0NDLmNvZmZlZSIsIi4uLy4uLy4uLy4uLy4uL1VzZXJzL2pvc2htdHVja2VyL0dpdEh1Yi9BU0NDL0FTQ0MuZnJhbWVyL21vZHVsZXMvQVNDQy5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtBQ0NBLElBQUEsc0ZBQUE7O0FBQUEsT0FBQSxHQUFVLEVBQVYsQ0FBQTs7QUFBQSxPQUdBLEdBQVUsR0FIVixDQUFBOztBQUFBLFFBTUEsR0FBVyxDQU5YLENBQUE7O0FBQUEsT0FTTyxDQUFDLE9BQVIsR0FBa0IsSUFUbEIsQ0FBQTs7QUFBQSxPQVlPLENBQUMsV0FBUixHQUFzQixHQVp0QixDQUFBOztBQUFBLE9BZU8sQ0FBQyxrQkFBUixHQUE2QixLQWY3QixDQUFBOztBQUFBLE9Bb0JPLENBQUMsV0FBUixHQUFzQixTQUFDLE9BQUQsRUFBVSxPQUFWLEVBQW1CLElBQW5CLEVBQXlCLE9BQXpCLEVBQWtDLEtBQWxDLEVBQXlDLFdBQXpDLEVBQXNELEtBQXRELEdBQUE7QUFDckIsRUFBQSxPQUFPLENBQUMsU0FBUyxDQUFDLE9BQWxCLEdBQTRCLEtBQTVCLENBQUE7QUFBQSxFQUNBLE9BQU8sQ0FBQyxFQUFSLENBQVcsTUFBTSxDQUFDLEtBQWxCLEVBQXlCLFNBQUEsR0FBQTtBQUN4QixJQUFBLE9BQU8sQ0FBQyxXQUFSLENBQUEsQ0FBQSxDQUFBO0FBQUEsSUFDQSxPQUFPLENBQUMsV0FBUixDQUFBLENBREEsQ0FBQTtBQUFBLElBRUEsSUFBSSxDQUFDLFdBQUwsQ0FBQSxDQUZBLENBQUE7QUFBQSxJQUdBLEtBQUssQ0FBQyxXQUFOLENBQUEsQ0FIQSxDQUFBO0FBQUEsSUFLQSxPQUFPLENBQUMsV0FBUixDQUFBLENBTEEsQ0FBQTtBQUFBLElBUUEsT0FBTyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQWQsQ0FBc0IsS0FBdEIsRUFBNkI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTdCLENBUkEsQ0FBQTtBQUFBLElBU0EsT0FBTyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQWQsQ0FBc0IsS0FBdEIsRUFBNkI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTdCLENBVEEsQ0FBQTtBQUFBLElBVUEsSUFBSSxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQVgsQ0FBbUIsS0FBbkIsRUFBMEI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTFCLENBVkEsQ0FBQTtBQUFBLElBV0EsS0FBSyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQVosQ0FBb0IsS0FBcEIsRUFBMkI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTNCLENBWEEsQ0FBQTtBQUFBLElBYUEsT0FBTyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQWQsQ0FBc0IsS0FBdEIsQ0FiQSxDQUFBO0FBQUEsSUFlQSxPQUFPLENBQUMsU0FBUyxDQUFDLE9BQWxCLEdBQTRCLElBZjVCLENBRHdCO0VBQUEsQ0FBekIsQ0FEQSxDQUFBO1NBcUJBLFdBQVcsQ0FBQyxFQUFaLENBQWUsTUFBTSxDQUFDLEtBQXRCLEVBQTZCLFNBQUEsR0FBQTtBQUM1QixJQUFBLE9BQU8sQ0FBQyxXQUFSLENBQUEsQ0FBQSxDQUFBO0FBQUEsSUFDQSxPQUFPLENBQUMsV0FBUixDQUFBLENBREEsQ0FBQTtBQUFBLElBRUEsSUFBSSxDQUFDLFdBQUwsQ0FBQSxDQUZBLENBQUE7QUFBQSxJQUdBLEtBQUssQ0FBQyxXQUFOLENBQUEsQ0FIQSxDQUFBO0FBQUEsSUFLQSxPQUFPLENBQUMsV0FBUixDQUFBLENBTEEsQ0FBQTtBQUFBLElBT0EsT0FBTyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQWQsQ0FBc0IsS0FBdEIsRUFBNkI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTdCLENBUEEsQ0FBQTtBQUFBLElBUUEsT0FBTyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQWQsQ0FBc0IsS0FBdEIsRUFBNkI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTdCLENBUkEsQ0FBQTtBQUFBLElBU0EsSUFBSSxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQVgsQ0FBbUIsS0FBbkIsRUFBMEI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTFCLENBVEEsQ0FBQTtBQUFBLElBVUEsS0FBSyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQVosQ0FBb0IsS0FBcEIsRUFBMkI7QUFBQSxNQUFDLEtBQUEsRUFBTyxLQUFSO0tBQTNCLENBVkEsQ0FBQTtBQUFBLElBWUEsT0FBTyxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQWQsQ0FBc0IsS0FBdEIsQ0FaQSxDQUFBO0FBQUEsSUFjQSxPQUFPLENBQUMsU0FBUyxDQUFDLE9BQWxCLEdBQTRCLElBZDVCLENBRDRCO0VBQUEsQ0FBN0IsRUF0QnFCO0FBQUEsQ0FwQnRCLENBQUE7O0FBQUEsT0E4RE8sQ0FBQyxpQkFBUixHQUE0QixTQUFDLEtBQUQsRUFBUSxPQUFSLEVBQWlCLGFBQWpCLEVBQWdDLE9BQWhDLEVBQXlDLE9BQXpDLEdBQUE7QUFDM0IsTUFBQSw2Q0FBQTtBQUFBLEVBQUEsSUFBRyxPQUFPLENBQUMsTUFBUixHQUFpQixDQUFwQjtBQUNDLFdBQU8sQ0FBUCxDQUREO0dBQUE7QUFBQSxFQUdBLElBQUEsR0FBTyxPQUFRLGNBQVEsQ0FBQSxDQUFBLENBSHZCLENBQUE7QUFBQSxFQUlBLElBQUEsR0FBTyxPQUFRLFVBQVEsQ0FBQSxDQUFBLENBSnZCLENBQUE7QUFBQSxFQUtBLElBQUEsR0FBTyxJQUFJLENBQUMsQ0FBTCxHQUFTLElBQUksQ0FBQyxDQUxyQixDQUFBO0FBQUEsRUFPQSxRQUFBLEdBQVcsQ0FBQyxDQUFDLElBQUksQ0FBQyxDQUFMLEdBQVMsSUFBSSxDQUFDLENBQWYsQ0FBQSxHQUFrQixJQUFuQixDQUFBLEdBQTJCLENBQUEsQ0FQdEMsQ0FBQTtBQUFBLEVBU0EsaUJBQUEsR0FBeUIsSUFBQSxJQUFBLENBQUEsQ0FBTSxDQUFDLE9BQVAsQ0FBQSxDQUFKLEdBQXVCLElBQUksQ0FBQyxDQVRqRCxDQUFBO0FBV0EsRUFBQSxJQUFHLGlCQUFBLEdBQW9CLE9BQXZCO0FBQ0MsV0FBTyxDQUFQLENBREQ7R0FYQTtBQWNBLEVBQUEsSUFBRyxLQUFBLENBQU0sUUFBTixDQUFBLEtBQW1CLElBQXRCO0FBQ0MsV0FBTyxDQUFQLENBREQ7R0FkQTtBQUFBLEVBaUJBLE9BQU8sQ0FBQyxJQUFSLENBQWEsbUJBQWIsRUFBa0MsS0FBbEMsRUFBeUMsT0FBekMsRUFBa0QsT0FBbEQsRUFBMkQsT0FBM0QsQ0FqQkEsQ0FBQTtBQUFBLEVBa0JBLE9BQU8sQ0FBQyxJQUFSLENBQWEsZUFBYixFQUE4QixRQUE5QixFQUF3QyxPQUF4QyxFQUFpRCxhQUFqRCxDQWxCQSxDQUFBO0FBb0JBLFNBQU8sUUFBUCxDQXJCMkI7QUFBQSxDQTlENUIsQ0FBQTs7QUFBQSxPQXNGTyxDQUFDLGFBQVIsR0FBd0IsU0FBQyxLQUFELEVBQVEsTUFBUixFQUFnQixNQUFoQixHQUFBO0FBQ3ZCLEVBQUEsS0FBSyxDQUFDLFNBQVMsQ0FBQyxPQUFoQixHQUEwQixJQUExQixDQUFBO0FBQUEsRUFDQSxLQUFLLENBQUMsU0FBUyxDQUFDLE1BQWhCLEdBQXlCLE1BRHpCLENBQUE7U0FFQSxLQUFLLENBQUMsU0FBUyxDQUFDLE1BQWhCLEdBQXlCLE9BSEY7QUFBQSxDQXRGeEIsQ0FBQTs7QUFBQSxPQTRGTyxDQUFDLGVBQVIsR0FBMEIsU0FBQSxHQUFBO0FBQ3pCLE1BQUEsUUFBQTtBQUFBLEVBQUEsUUFBUSxDQUFDLG1CQUFULENBQTZCLE1BQU0sQ0FBQyxTQUFwQyxFQUErQyxlQUEvQyxDQUFBLENBQUE7QUFBQSxFQUNBLE9BQU8sQ0FBQyxPQUFSLEdBQWtCLElBRGxCLENBQUE7QUFBQSxFQUVBLE9BQUEsR0FBVSxFQUZWLENBQUE7U0FHQSxRQUFBLEdBQVcsRUFKYztBQUFBLENBNUYxQixDQUFBOztBQUFBLE9BbUdPLENBQUMsWUFBUixHQUF1QixTQUFDLE9BQUQsR0FBQTtBQUN0QixFQUFBLFFBQVEsQ0FBQyxnQkFBVCxDQUEwQixNQUFNLENBQUMsU0FBakMsRUFBNEMsZUFBNUMsQ0FBQSxDQUFBO0FBQUEsRUFDQSxPQUFPLENBQUMsSUFBUixDQUFhLGVBQWIsRUFBOEIsY0FBOUIsQ0FEQSxDQUFBO1NBRUEsT0FBTyxDQUFDLEVBQVIsQ0FBVyxtQkFBWCxFQUFnQyxrQkFBaEMsRUFIc0I7QUFBQSxDQW5HdkIsQ0FBQTs7QUFBQSxrQkEyR0EsR0FBcUIsU0FBQyxLQUFELEVBQVEsT0FBUixFQUFpQixPQUFqQixFQUEwQixPQUExQixHQUFBO0FBQ3BCLEVBQUEsUUFBQSxHQUFXLE9BQUEsR0FBVSxLQUFLLENBQUMsS0FBM0IsQ0FBQTtBQUVBLEVBQUEsSUFBRyxPQUFPLENBQUMsT0FBUixLQUFtQixNQUF0QjtXQUNDLEtBQUEsQ0FBTSxRQUFOLEVBQWdCLE9BQWhCLEVBQXlCLE9BQXpCLEVBREQ7R0FBQSxNQUFBO0FBQUE7R0FIb0I7QUFBQSxDQTNHckIsQ0FBQTs7QUFBQSxLQWtIQSxHQUFRLFNBQUMsUUFBRCxFQUFXLE9BQVgsRUFBb0IsT0FBcEIsR0FBQTtBQUNQLEVBQUEsT0FBTyxDQUFDLEtBQVIsR0FBZ0IsS0FBSyxDQUFDLFFBQU4sQ0FBZSxRQUFmLEVBQXlCLENBQUMsQ0FBRCxFQUFJLEdBQUosQ0FBekIsRUFBbUMsQ0FBQyxDQUFELEVBQUksS0FBSixDQUFuQyxFQUErQyxJQUEvQyxDQUFoQixDQUFBO1NBQ0EsT0FBTyxDQUFDLE9BQVIsR0FBa0IsS0FBSyxDQUFDLFFBQU4sQ0FBZSxPQUFPLENBQUMsS0FBdkIsRUFBOEIsQ0FBQyxHQUFELEVBQU0sS0FBTixDQUE5QixFQUE0QyxDQUFDLENBQUQsRUFBSSxDQUFKLENBQTVDLEVBQW9ELElBQXBELEVBRlg7QUFBQSxDQWxIUixDQUFBOztBQUFBLGNBc0hBLEdBQWlCLFNBQUMsUUFBRCxFQUFXLE9BQVgsRUFBb0IsYUFBcEIsR0FBQTtBQUNoQixFQUFBLElBQUcsUUFBQSxHQUFXLE9BQU8sQ0FBQyxrQkFBbkIsSUFBeUMsUUFBQSxHQUFXLE9BQU8sQ0FBQyxXQUEvRDtXQUNDLE9BQU8sQ0FBQyxPQUFSLEdBQWtCLE9BRG5CO0dBQUEsTUFBQTtBQUdDLElBQUEsT0FBTyxDQUFDLFNBQVMsQ0FBQyxPQUFsQixHQUE0QixLQUE1QixDQUFBO1dBQ0EsYUFBYSxDQUFDLE1BQU0sQ0FBQyxRQUFELENBQXBCLENBQTRCLE1BQTVCLEVBQW9DO0FBQUEsTUFBQyxLQUFBLEVBQU8sb0JBQVI7S0FBcEMsRUFKRDtHQURnQjtBQUFBLENBdEhqQixDQUFBOztBQUFBLGVBNkhBLEdBQWtCLFNBQUMsS0FBRCxHQUFBO0FBQ2pCLE1BQUEsWUFBQTtBQUFBLEVBQUEsWUFBQSxHQUNDO0FBQUEsSUFBQSxDQUFBLEVBQUcsS0FBSyxDQUFDLEtBQVQ7QUFBQSxJQUNBLENBQUEsRUFBRyxLQUFLLENBQUMsU0FEVDtHQURELENBQUE7U0FJQSxPQUFPLENBQUMsSUFBUixDQUFhLFlBQWIsRUFMaUI7QUFBQSxDQTdIbEIsQ0FBQTs7Ozs7QUNEQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSIsImZpbGUiOiJnZW5lcmF0ZWQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlc0NvbnRlbnQiOlsiKGZ1bmN0aW9uIGUodCxuLHIpe2Z1bmN0aW9uIHMobyx1KXtpZighbltvXSl7aWYoIXRbb10pe3ZhciBhPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7aWYoIXUmJmEpcmV0dXJuIGEobywhMCk7aWYoaSlyZXR1cm4gaShvLCEwKTt2YXIgZj1uZXcgRXJyb3IoXCJDYW5ub3QgZmluZCBtb2R1bGUgJ1wiK28rXCInXCIpO3Rocm93IGYuY29kZT1cIk1PRFVMRV9OT1RfRk9VTkRcIixmfXZhciBsPW5bb109e2V4cG9ydHM6e319O3Rbb11bMF0uY2FsbChsLmV4cG9ydHMsZnVuY3Rpb24oZSl7dmFyIG49dFtvXVsxXVtlXTtyZXR1cm4gcyhuP246ZSl9LGwsbC5leHBvcnRzLGUsdCxuLHIpfXJldHVybiBuW29dLmV4cG9ydHN9dmFyIGk9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtmb3IodmFyIG89MDtvPHIubGVuZ3RoO28rKylzKHJbb10pO3JldHVybiBzfSkiLCIjIFN0b3JlIGNoYW5nZXMgaW4geSBhbmQgdGltZSBmb3IgdmVsb2NpdHlcbl9kZWx0YXMgPSBbXVxuXG4jIFZlbG9jaXR5IHRpbWVvdXRcbnRpbWVPdXQgPSAxMDBcblxuIyBEaXN0YW5jZSB2YXJpYWJsZVxuZGlzdGFuY2UgPSAwXG5cbiMgV2hpY2ggZ2VzdHVyZSB3YXMgdXNlZFxuZXhwb3J0cy5nZXN0dXJlID0gbnVsbFxuXG4jIFNldCBkaXN0YW5jZSB0aHJlc2hvbGRcbmV4cG9ydHMubWluRGlzdGFuY2UgPSAxMTBcblxuIyBTZXQgdmVsb2NpdHkgdGhyZXNob2xkXG5leHBvcnRzLm1pbkdlc3R1cmVWZWxvY2l0eSA9IDEuNzg2XG5cbiMg4oCT4oCT4oCTIEVYUE9SVCBGVU5DVElPTlNcblxuIyBJbnRlcmFjdGlvbiBmb3IgYXBwU3dpdGNoZXJcbmV4cG9ydHMuYXBwU3dpdGNoZXIgPSAoY2FsY2JvdCwgc3BvdGlmeSwgYWx0bywgcmVjZW50cywgaWNvbnMsIGNhbGNib3RJY29uLCBjdXJ2ZSkgLT5cblx0Y2FsY2JvdC5kcmFnZ2FibGUuZW5hYmxlZCA9IGZhbHNlXG5cdGNhbGNib3Qub24gRXZlbnRzLkNsaWNrLCAtPlxuXHRcdGNhbGNib3QuYW5pbWF0ZVN0b3AoKVxuXHRcdHNwb3RpZnkuYW5pbWF0ZVN0b3AoKVxuXHRcdGFsdG8uYW5pbWF0ZVN0b3AoKVxuXHRcdGljb25zLmFuaW1hdGVTdG9wKClcblxuXHRcdHJlY2VudHMuYW5pbWF0ZVN0b3AoKVxuXG5cblx0XHRjYWxjYm90LnN0YXRlcy5zd2l0Y2ggXCJhcHBcIiwge2N1cnZlOiBjdXJ2ZX1cblx0XHRzcG90aWZ5LnN0YXRlcy5zd2l0Y2ggXCJhcHBcIiwge2N1cnZlOiBjdXJ2ZX1cblx0XHRhbHRvLnN0YXRlcy5zd2l0Y2ggXCJhcHBcIiwge2N1cnZlOiBjdXJ2ZX1cblx0XHRpY29ucy5zdGF0ZXMuc3dpdGNoIFwiYXBwXCIsIHtjdXJ2ZTogY3VydmV9XG5cblx0XHRyZWNlbnRzLnN0YXRlcy5zd2l0Y2ggXCJhcHBcIlxuXG5cdFx0Y2FsY2JvdC5kcmFnZ2FibGUuZW5hYmxlZCA9IHRydWVcblxuXHRcdHJldHVyblxuXG5cdGNhbGNib3RJY29uLm9uIEV2ZW50cy5DbGljaywgLT5cblx0XHRjYWxjYm90LmFuaW1hdGVTdG9wKClcblx0XHRzcG90aWZ5LmFuaW1hdGVTdG9wKClcblx0XHRhbHRvLmFuaW1hdGVTdG9wKClcblx0XHRpY29ucy5hbmltYXRlU3RvcCgpXG5cblx0XHRyZWNlbnRzLmFuaW1hdGVTdG9wKClcblx0XHRcblx0XHRjYWxjYm90LnN0YXRlcy5zd2l0Y2ggXCJhcHBcIiwge2N1cnZlOiBjdXJ2ZX1cblx0XHRzcG90aWZ5LnN0YXRlcy5zd2l0Y2ggXCJhcHBcIiwge2N1cnZlOiBjdXJ2ZX1cblx0XHRhbHRvLnN0YXRlcy5zd2l0Y2ggXCJhcHBcIiwge2N1cnZlOiBjdXJ2ZX1cblx0XHRpY29ucy5zdGF0ZXMuc3dpdGNoIFwiYXBwXCIsIHtjdXJ2ZTogY3VydmV9XG5cblx0XHRyZWNlbnRzLnN0YXRlcy5zd2l0Y2ggXCJhcHBcIlxuXG5cdFx0Y2FsY2JvdC5kcmFnZ2FibGUuZW5hYmxlZCA9IHRydWVcblxuXHRcdHJldHVyblxuXG4jIENhbGN1bGF0ZSBob3cgZmFzdCBnZXN0dXJlIG1vdmVzIChpbmNsdWRlcyBkaXJlY3Rpb24pXG5leHBvcnRzLmNhbGN1bGF0ZVZlbG9jaXR5ID0gKGV2ZW50LCBjYWxjYm90LCBjb250cm9sQ2VudGVyLCByZWNlbnRzLCBvcmlnaW5ZKSAtPlxuXHRpZiBfZGVsdGFzLmxlbmd0aCA8IDJcblx0XHRyZXR1cm4gMFxuXG5cdGN1cnIgPSBfZGVsdGFzWy0yLi4tMl1bMF1cblx0cHJldiA9IF9kZWx0YXNbLTEuLi0xXVswXVxuXHR0aW1lID0gY3Vyci50IC0gcHJldi50XG5cblx0dmVsb2NpdHkgPSAoKGN1cnIueSAtIHByZXYueSkvdGltZSkgKiAtMVxuXG5cdHRpbWVTaW5jZUxhc3RNb3ZlID0gKG5ldyBEYXRlKCkuZ2V0VGltZSgpIC0gcHJldi50KVxuXG5cdGlmIHRpbWVTaW5jZUxhc3RNb3ZlID4gdGltZU91dFxuXHRcdHJldHVybiAwXG5cblx0aWYgaXNOYU4odmVsb2NpdHkpIGlzIHRydWVcblx0XHRyZXR1cm4gMFxuXHRcblx0Y2FsY2JvdC5lbWl0IFwiY2FsY3VsYXRlRGlzdGFuY2VcIiwgZXZlbnQsIGNhbGNib3QsIHJlY2VudHMsIG9yaWdpbllcblx0Y2FsY2JvdC5lbWl0IFwiY2hvb3NlR2VzdHVyZVwiLCB2ZWxvY2l0eSwgY2FsY2JvdCwgY29udHJvbENlbnRlclxuXG5cdHJldHVybiB2ZWxvY2l0eVxuXG4jIEdpdmUgYSBsYXllciBkcmFnZ2FibGUgcHJvcGVydGllc1xuZXhwb3J0cy5tYWtlRHJhZ2dhYmxlID0gKGxheWVyLCBzcGVlZFgsIHNwZWVkWSkgLT5cblx0bGF5ZXIuZHJhZ2dhYmxlLmVuYWJsZWQgPSB0cnVlXG5cdGxheWVyLmRyYWdnYWJsZS5zcGVlZFggPSBzcGVlZFhcblx0bGF5ZXIuZHJhZ2dhYmxlLnNwZWVkWSA9IHNwZWVkWVxuXG4jIFJlbW92ZSBsaXN0ZW5lcnMgZm9yIHVwZGF0aW5nIHZhbHVlc1xuZXhwb3J0cy5yZW1vdmVMaXN0ZW5lcnMgPSAtPlxuXHRkb2N1bWVudC5yZW1vdmVFdmVudExpc3RlbmVyIEV2ZW50cy5Ub3VjaE1vdmUsIF91cGRhdGVWZWxvY2l0eVxuXHRleHBvcnRzLmdlc3R1cmUgPSBudWxsXG5cdF9kZWx0YXMgPSBbXVxuXHR2ZWxvY2l0eSA9IDBcblxuIyBBZGQgbGlzdGVuZXJzIGZvciB1cGRhdGluZyB2YWx1ZXNcbmV4cG9ydHMuYWRkTGlzdGVuZXJzID0gKGNhbGNib3QpIC0+XG5cdGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIgRXZlbnRzLlRvdWNoTW92ZSwgX3VwZGF0ZVZlbG9jaXR5XG5cdGNhbGNib3Qub25jZSBcImNob29zZUdlc3R1cmVcIiwgX2Nob29zZUdlc3R1cmVcblx0Y2FsY2JvdC5vbiBcImNhbGN1bGF0ZURpc3RhbmNlXCIsIF9jYWxjdWxhdGVEaXN0YW5jZVxuXG5cbiMg4oCT4oCT4oCTIExPQ0FMIEZVTkNUSU9OU1xuXG5fY2FsY3VsYXRlRGlzdGFuY2UgPSAoZXZlbnQsIGNhbGNib3QsIHJlY2VudHMsIG9yaWdpblkpIC0+XG5cdGRpc3RhbmNlID0gb3JpZ2luWSAtIGV2ZW50LnBhZ2VZXG5cblx0aWYgZXhwb3J0cy5nZXN0dXJlIGlzIFwiRHJhZ1wiXG5cdFx0X2RyYWcoZGlzdGFuY2UsIGNhbGNib3QsIHJlY2VudHMpXG5cdGVsc2VcblxuX2RyYWcgPSAoZGlzdGFuY2UsIGNhbGNib3QsIHJlY2VudHMpIC0+XG5cdGNhbGNib3Quc2NhbGUgPSBVdGlscy5tb2R1bGF0ZShkaXN0YW5jZSwgWzAsIDY1N10sIFsxLCAuNDg2N10sIHRydWUpXG5cdHJlY2VudHMub3BhY2l0eSA9IFV0aWxzLm1vZHVsYXRlKGNhbGNib3Quc2NhbGUsIFsuNzAsIC40ODY3XSwgWzAsIDFdLCB0cnVlKVxuXG5fY2hvb3NlR2VzdHVyZSA9ICh2ZWxvY2l0eSwgY2FsY2JvdCwgY29udHJvbENlbnRlcikgLT5cblx0aWYgdmVsb2NpdHkgPCBleHBvcnRzLm1pbkdlc3R1cmVWZWxvY2l0eSAmJiBkaXN0YW5jZSA8IGV4cG9ydHMubWluRGlzdGFuY2Vcblx0XHRleHBvcnRzLmdlc3R1cmUgPSBcIkRyYWdcIlxuXHRlbHNlXG5cdFx0Y2FsY2JvdC5kcmFnZ2FibGUuZW5hYmxlZCA9IGZhbHNlXG5cdFx0Y29udHJvbENlbnRlci5zdGF0ZXMuc3dpdGNoIFwib3BlblwiLCB7Y3VydmU6IFwic3ByaW5nKDU1MCwgMjUsIDApXCJ9IFxuXG5fdXBkYXRlVmVsb2NpdHkgPSAoZXZlbnQpIC0+XG5cdHVwZGF0ZWREZWx0YSA9IFxuXHRcdHk6IGV2ZW50LnBhZ2VZXG5cdFx0dDogZXZlbnQudGltZVN0YW1wXG5cblx0X2RlbHRhcy5wdXNoIHVwZGF0ZWREZWx0YVxuIiwiLy8gR2VuZXJhdGVkIGJ5IENvZmZlZVNjcmlwdCAxLjkuMVxudmFyIF9jYWxjdWxhdGVEaXN0YW5jZSwgX2Nob29zZUdlc3R1cmUsIF9kZWx0YXMsIF9kcmFnLCBfdXBkYXRlVmVsb2NpdHksIGRpc3RhbmNlLCB0aW1lT3V0O1xuXG5fZGVsdGFzID0gW107XG5cbnRpbWVPdXQgPSAxMDA7XG5cbmRpc3RhbmNlID0gMDtcblxuZXhwb3J0cy5nZXN0dXJlID0gbnVsbDtcblxuZXhwb3J0cy5taW5EaXN0YW5jZSA9IDExMDtcblxuZXhwb3J0cy5taW5HZXN0dXJlVmVsb2NpdHkgPSAxLjc4NjtcblxuZXhwb3J0cy5hcHBTd2l0Y2hlciA9IGZ1bmN0aW9uKGNhbGNib3QsIHNwb3RpZnksIGFsdG8sIHJlY2VudHMsIGljb25zLCBjYWxjYm90SWNvbiwgY3VydmUpIHtcbiAgY2FsY2JvdC5kcmFnZ2FibGUuZW5hYmxlZCA9IGZhbHNlO1xuICBjYWxjYm90Lm9uKEV2ZW50cy5DbGljaywgZnVuY3Rpb24oKSB7XG4gICAgY2FsY2JvdC5hbmltYXRlU3RvcCgpO1xuICAgIHNwb3RpZnkuYW5pbWF0ZVN0b3AoKTtcbiAgICBhbHRvLmFuaW1hdGVTdG9wKCk7XG4gICAgaWNvbnMuYW5pbWF0ZVN0b3AoKTtcbiAgICByZWNlbnRzLmFuaW1hdGVTdG9wKCk7XG4gICAgY2FsY2JvdC5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJhcHBcIiwge1xuICAgICAgY3VydmU6IGN1cnZlXG4gICAgfSk7XG4gICAgc3BvdGlmeS5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJhcHBcIiwge1xuICAgICAgY3VydmU6IGN1cnZlXG4gICAgfSk7XG4gICAgYWx0by5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJhcHBcIiwge1xuICAgICAgY3VydmU6IGN1cnZlXG4gICAgfSk7XG4gICAgaWNvbnMuc3RhdGVzW1wic3dpdGNoXCJdKFwiYXBwXCIsIHtcbiAgICAgIGN1cnZlOiBjdXJ2ZVxuICAgIH0pO1xuICAgIHJlY2VudHMuc3RhdGVzW1wic3dpdGNoXCJdKFwiYXBwXCIpO1xuICAgIGNhbGNib3QuZHJhZ2dhYmxlLmVuYWJsZWQgPSB0cnVlO1xuICB9KTtcbiAgcmV0dXJuIGNhbGNib3RJY29uLm9uKEV2ZW50cy5DbGljaywgZnVuY3Rpb24oKSB7XG4gICAgY2FsY2JvdC5hbmltYXRlU3RvcCgpO1xuICAgIHNwb3RpZnkuYW5pbWF0ZVN0b3AoKTtcbiAgICBhbHRvLmFuaW1hdGVTdG9wKCk7XG4gICAgaWNvbnMuYW5pbWF0ZVN0b3AoKTtcbiAgICByZWNlbnRzLmFuaW1hdGVTdG9wKCk7XG4gICAgY2FsY2JvdC5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJhcHBcIiwge1xuICAgICAgY3VydmU6IGN1cnZlXG4gICAgfSk7XG4gICAgc3BvdGlmeS5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJhcHBcIiwge1xuICAgICAgY3VydmU6IGN1cnZlXG4gICAgfSk7XG4gICAgYWx0by5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJhcHBcIiwge1xuICAgICAgY3VydmU6IGN1cnZlXG4gICAgfSk7XG4gICAgaWNvbnMuc3RhdGVzW1wic3dpdGNoXCJdKFwiYXBwXCIsIHtcbiAgICAgIGN1cnZlOiBjdXJ2ZVxuICAgIH0pO1xuICAgIHJlY2VudHMuc3RhdGVzW1wic3dpdGNoXCJdKFwiYXBwXCIpO1xuICAgIGNhbGNib3QuZHJhZ2dhYmxlLmVuYWJsZWQgPSB0cnVlO1xuICB9KTtcbn07XG5cbmV4cG9ydHMuY2FsY3VsYXRlVmVsb2NpdHkgPSBmdW5jdGlvbihldmVudCwgY2FsY2JvdCwgY29udHJvbENlbnRlciwgcmVjZW50cywgb3JpZ2luWSkge1xuICB2YXIgY3VyciwgcHJldiwgdGltZSwgdGltZVNpbmNlTGFzdE1vdmUsIHZlbG9jaXR5O1xuICBpZiAoX2RlbHRhcy5sZW5ndGggPCAyKSB7XG4gICAgcmV0dXJuIDA7XG4gIH1cbiAgY3VyciA9IF9kZWx0YXMuc2xpY2UoLTIsIC0xKVswXTtcbiAgcHJldiA9IF9kZWx0YXMuc2xpY2UoLTEpWzBdO1xuICB0aW1lID0gY3Vyci50IC0gcHJldi50O1xuICB2ZWxvY2l0eSA9ICgoY3Vyci55IC0gcHJldi55KSAvIHRpbWUpICogLTE7XG4gIHRpbWVTaW5jZUxhc3RNb3ZlID0gbmV3IERhdGUoKS5nZXRUaW1lKCkgLSBwcmV2LnQ7XG4gIGlmICh0aW1lU2luY2VMYXN0TW92ZSA+IHRpbWVPdXQpIHtcbiAgICByZXR1cm4gMDtcbiAgfVxuICBpZiAoaXNOYU4odmVsb2NpdHkpID09PSB0cnVlKSB7XG4gICAgcmV0dXJuIDA7XG4gIH1cbiAgY2FsY2JvdC5lbWl0KFwiY2FsY3VsYXRlRGlzdGFuY2VcIiwgZXZlbnQsIGNhbGNib3QsIHJlY2VudHMsIG9yaWdpblkpO1xuICBjYWxjYm90LmVtaXQoXCJjaG9vc2VHZXN0dXJlXCIsIHZlbG9jaXR5LCBjYWxjYm90LCBjb250cm9sQ2VudGVyKTtcbiAgcmV0dXJuIHZlbG9jaXR5O1xufTtcblxuZXhwb3J0cy5tYWtlRHJhZ2dhYmxlID0gZnVuY3Rpb24obGF5ZXIsIHNwZWVkWCwgc3BlZWRZKSB7XG4gIGxheWVyLmRyYWdnYWJsZS5lbmFibGVkID0gdHJ1ZTtcbiAgbGF5ZXIuZHJhZ2dhYmxlLnNwZWVkWCA9IHNwZWVkWDtcbiAgcmV0dXJuIGxheWVyLmRyYWdnYWJsZS5zcGVlZFkgPSBzcGVlZFk7XG59O1xuXG5leHBvcnRzLnJlbW92ZUxpc3RlbmVycyA9IGZ1bmN0aW9uKCkge1xuICB2YXIgdmVsb2NpdHk7XG4gIGRvY3VtZW50LnJlbW92ZUV2ZW50TGlzdGVuZXIoRXZlbnRzLlRvdWNoTW92ZSwgX3VwZGF0ZVZlbG9jaXR5KTtcbiAgZXhwb3J0cy5nZXN0dXJlID0gbnVsbDtcbiAgX2RlbHRhcyA9IFtdO1xuICByZXR1cm4gdmVsb2NpdHkgPSAwO1xufTtcblxuZXhwb3J0cy5hZGRMaXN0ZW5lcnMgPSBmdW5jdGlvbihjYWxjYm90KSB7XG4gIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoRXZlbnRzLlRvdWNoTW92ZSwgX3VwZGF0ZVZlbG9jaXR5KTtcbiAgY2FsY2JvdC5vbmNlKFwiY2hvb3NlR2VzdHVyZVwiLCBfY2hvb3NlR2VzdHVyZSk7XG4gIHJldHVybiBjYWxjYm90Lm9uKFwiY2FsY3VsYXRlRGlzdGFuY2VcIiwgX2NhbGN1bGF0ZURpc3RhbmNlKTtcbn07XG5cbl9jYWxjdWxhdGVEaXN0YW5jZSA9IGZ1bmN0aW9uKGV2ZW50LCBjYWxjYm90LCByZWNlbnRzLCBvcmlnaW5ZKSB7XG4gIGRpc3RhbmNlID0gb3JpZ2luWSAtIGV2ZW50LnBhZ2VZO1xuICBpZiAoZXhwb3J0cy5nZXN0dXJlID09PSBcIkRyYWdcIikge1xuICAgIHJldHVybiBfZHJhZyhkaXN0YW5jZSwgY2FsY2JvdCwgcmVjZW50cyk7XG4gIH0gZWxzZSB7XG5cbiAgfVxufTtcblxuX2RyYWcgPSBmdW5jdGlvbihkaXN0YW5jZSwgY2FsY2JvdCwgcmVjZW50cykge1xuICBjYWxjYm90LnNjYWxlID0gVXRpbHMubW9kdWxhdGUoZGlzdGFuY2UsIFswLCA2NTddLCBbMSwgLjQ4NjddLCB0cnVlKTtcbiAgcmV0dXJuIHJlY2VudHMub3BhY2l0eSA9IFV0aWxzLm1vZHVsYXRlKGNhbGNib3Quc2NhbGUsIFsuNzAsIC40ODY3XSwgWzAsIDFdLCB0cnVlKTtcbn07XG5cbl9jaG9vc2VHZXN0dXJlID0gZnVuY3Rpb24odmVsb2NpdHksIGNhbGNib3QsIGNvbnRyb2xDZW50ZXIpIHtcbiAgaWYgKHZlbG9jaXR5IDwgZXhwb3J0cy5taW5HZXN0dXJlVmVsb2NpdHkgJiYgZGlzdGFuY2UgPCBleHBvcnRzLm1pbkRpc3RhbmNlKSB7XG4gICAgcmV0dXJuIGV4cG9ydHMuZ2VzdHVyZSA9IFwiRHJhZ1wiO1xuICB9IGVsc2Uge1xuICAgIGNhbGNib3QuZHJhZ2dhYmxlLmVuYWJsZWQgPSBmYWxzZTtcbiAgICByZXR1cm4gY29udHJvbENlbnRlci5zdGF0ZXNbXCJzd2l0Y2hcIl0oXCJvcGVuXCIsIHtcbiAgICAgIGN1cnZlOiBcInNwcmluZyg1NTAsIDI1LCAwKVwiXG4gICAgfSk7XG4gIH1cbn07XG5cbl91cGRhdGVWZWxvY2l0eSA9IGZ1bmN0aW9uKGV2ZW50KSB7XG4gIHZhciB1cGRhdGVkRGVsdGE7XG4gIHVwZGF0ZWREZWx0YSA9IHtcbiAgICB5OiBldmVudC5wYWdlWSxcbiAgICB0OiBldmVudC50aW1lU3RhbXBcbiAgfTtcbiAgcmV0dXJuIF9kZWx0YXMucHVzaCh1cGRhdGVkRGVsdGEpO1xufTtcbiJdfQ==
